export const photoLinks = [
  "https://res.cloudinary.com/drmyjm4wm/image/upload/v1722656219/Screenshot1_bv1oht.jpg",
  "https://res.cloudinary.com/drmyjm4wm/image/upload/v1722656219/Screenshot2_bwhsnp.jpg",
  "https://res.cloudinary.com/drmyjm4wm/image/upload/v1722656219/Screenshot0_um2jvo.jpg",
];

export const photoRequestPhrases = [
  "show me your photos",
  "show me some photos",
  "show me some your images",
  "can I see your photos",
  "can you show me your photos",
  "can you show me your pictures",
  "can I see some photos",
  "do you have any photos",
  "share your photos",
  "photos please",
  "I want to see your photos",
  "I want to see your images",
  "I want to see some photos",
  "I want to see your pictures",
  "I want to see some pictures",
  "I want to see some of your pictures",
  "show me pictures",
  "can I view your photos",
  "display your photos",
  "can you show me photos",
  "photos",
  "pictures",
];
